eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
keycloak:
  auth-server-url: https://login.archi-lab.io/auth
  bearer-only: true
  cors: false
  principal-attribute: preferred_username
  public-client: false
  realm: archilab
  resource: search-service
import:
  delay:
    seconds: 10
    initial:
      seconds: 1
searchNames:
  title: title
  supervisorName: supervisorName
  requirements: requirements
  shortDescription: shortDescription
  description: description
  tags: tags
searchMultiplier:
  tagMultiplier: 5;
  descriptionMultiplier: 8;
  shortDescriptionMultiplier: 2;
  requirementsMultiplier: 4;
  supervisorNameMultiplier: 3;
  titleMultiplier: 2;
server:
  port: 9004
  use-forward-headers: true
spring:
  application:
    name: search-service
  datasource:
    password: search-service
    url: jdbc:postgresql://search-db:5432/search-db
    username: search-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
